import React from 'react';
import Container from '../../Components/Container';
import Navbar from '../../Components/Navbar/home-nav';
import Sticky from 'react-stickynode';

const Home = () => {
    return ( 
        <div>
            <Sticky top={0} innerZ={9999} activeClass="sticky-nav-active">
                <Navbar bg='#0080ff' color="#ffffff"/>
            </Sticky>
            <Container fullWidth={true}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu lobortis elementum nibh tellus molestie. Vitae nunc sed velit dignissim sodales ut eu sem integer. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Gravida in fermentum et sollicitudin ac. Sit amet tellus cras adipiscing. Neque convallis a cras semper auctor neque vitae tempus quam. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Nibh ipsum consequat nisl vel pretium lectus. Augue interdum velit euismod in pellentesque. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Ipsum dolor sit amet consectetur. Eu feugiat pretium nibh ipsum consequat nisl vel.

Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Lacus sed turpis tincidunt id aliquet risus feugiat. Sed turpis tincidunt id aliquet risus. Aliquam nulla facilisi cras fermentum odio eu feugiat. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Diam volutpat commodo sed egestas. Eget sit amet tellus cras adipiscing. At erat pellentesque adipiscing commodo. At imperdiet dui accumsan sit amet nulla facilisi. Pulvinar elementum integer enim neque. Et netus et malesuada fames ac turpis egestas sed tempus. Malesuada bibendum arcu vitae elementum curabitur vitae. Vitae purus faucibus ornare suspendisse sed nisi lacus. Tincidunt arcu non sodales neque sodales ut etiam. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Aliquam nulla facilisi cras fermentum odio eu. Justo laoreet sit amet cursus sit amet. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non.

Feugiat nibh sed pulvinar proin gravida hendrerit. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Enim nec dui nunc mattis enim ut tellus. Neque ornare aenean euismod elementum nisi quis eleifend. Viverra tellus in hac habitasse platea. Consequat semper viverra nam libero justo. Faucibus pulvinar elementum integer enim neque. Lacinia quis vel eros donec ac odio tempor orci. Auctor urna nunc id cursus metus aliquam. Sagittis purus sit amet volutpat consequat. Egestas erat imperdiet sed euismod nisi porta lorem. Congue nisi vitae suscipit tellus mauris. Scelerisque eleifend donec pretium vulputate sapien. Aliquam faucibus purus in massa tempor. Arcu dictum varius duis at consectetur lorem donec.

Aliquet porttitor lacus luctus accumsan tortor posuere. Scelerisque purus semper eget duis at tellus at urna condimentum. Morbi tristique senectus et netus et malesuada fames ac. Diam vel quam elementum pulvinar etiam non quam lacus. Nibh mauris cursus mattis molestie a iaculis. Amet consectetur adipiscing elit pellentesque. Amet dictum sit amet justo donec enim diam vulputate ut. Amet facilisis magna etiam tempor orci eu. Senectus et netus et malesuada fames ac turpis. Magna sit amet purus gravida quis blandit turpis cursus. In nulla posuere sollicitudin aliquam ultrices sagittis orci.

Egestas integer eget aliquet nibh praesent tristique magna sit amet. Nibh nisl condimentum id venenatis a condimentum vitae. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Cras ornare arcu dui vivamus arcu felis. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Posuere urna nec tincidunt praesent semper feugiat nibh. Sagittis orci a scelerisque purus. Fringilla ut morbi tincidunt augue. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Tortor posuere ac ut consequat semper viverra nam libero. Erat nam at lectus urna duis.

Et netus et malesuada fames ac turpis egestas sed tempus. Mi sit amet mauris commodo quis imperdiet massa. Ipsum suspendisse ultrices gravida dictum. Nunc sed velit dignissim sodales ut eu sem integer vitae. Urna cursus eget nunc scelerisque viverra mauris. Vulputate eu scelerisque felis imperdiet. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Malesuada nunc vel risus commodo viverra maecenas accumsan. Nunc sed velit dignissim sodales ut eu sem. At volutpat diam ut venenatis tellus in metus. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Urna molestie at elementum eu facilisis sed odio morbi quis. Vivamus arcu felis bibendum ut tristique et. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Faucibus nisl tincidunt eget nullam non nisi est. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Vitae suscipit tellus mauris a diam. Pretium lectus quam id leo in vitae turpis. Nisi quis eleifend quam adipiscing vitae proin sagittis. Eu mi bibendum neque egestas congue.

Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Scelerisque varius morbi enim nunc faucibus a. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Consectetur purus ut faucibus pulvinar elementum integer. Leo a diam sollicitudin tempor id eu nisl. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Sit amet consectetur adipiscing elit duis tristique. Orci porta non pulvinar neque laoreet suspendisse interdum. Mauris vitae ultricies leo integer malesuada nunc. Pellentesque nec nam aliquam sem. Tortor vitae purus faucibus ornare suspendisse. Est sit amet facilisis magna etiam tempor. In fermentum et sollicitudin ac orci. Viverra maecenas accumsan lacus vel facilisis volutpat est velit.

Nunc consequat interdum varius sit amet mattis. Ipsum a arcu cursus vitae congue mauris rhoncus. Nulla facilisi morbi tempus iaculis. A iaculis at erat pellentesque adipiscing commodo elit at. Pretium viverra suspendisse potenti nullam ac. Imperdiet dui accumsan sit amet nulla. Metus dictum at tempor commodo ullamcorper a lacus vestibulum sed. Dui nunc mattis enim ut tellus elementum sagittis. Commodo sed egestas egestas fringilla phasellus faucibus. Morbi leo urna molestie at elementum eu facilisis. Vel pretium lectus quam id. Ut diam quam nulla porttitor massa id neque aliquam.

Nec sagittis aliquam malesuada bibendum. Sit amet consectetur adipiscing elit pellentesque habitant. Tellus molestie nunc non blandit. Mi bibendum neque egestas congue quisque egestas. Purus sit amet volutpat consequat mauris nunc. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Enim sed faucibus turpis in. Nullam non nisi est sit amet facilisis magna etiam. Vestibulum rhoncus est pellentesque elit ullamcorper. Integer malesuada nunc vel risus commodo viverra maecenas. Augue lacus viverra vitae congue eu. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Scelerisque in dictum non consectetur a erat. Bibendum arcu vitae elementum curabitur vitae. Et odio pellentesque diam volutpat commodo sed egestas. Scelerisque purus semper eget duis at tellus at. At varius vel pharetra vel turpis nunc eget lorem. Integer quis auctor elit sed vulputate mi sit amet mauris.

Rutrum quisque non tellus orci ac auctor augue mauris augue. Venenatis a condimentum vitae sapien pellentesque habitant morbi. Malesuada proin libero nunc consequat interdum varius sit. Odio aenean sed adipiscing diam donec adipiscing. Senectus et netus et malesuada fames. Massa sed elementum tempus egestas sed sed. Praesent semper feugiat nibh sed pulvinar. Fermentum et sollicitudin ac orci phasellus egestas tellus. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Nibh nisl condimentum id venenatis a. Amet cursus sit amet dictum sit. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Orci eu lobortis elementum nibh tellus. Ornare lectus sit amet est placerat in egestas erat imperdiet. Arcu non odio euismod lacinia at. Id donec ultrices tincidunt arcu non sodales. Parturient montes nascetur ridiculus mus mauris vitae ultricies. Sem fringilla ut morbi tincidunt. Tellus at urna condimentum mattis pellentesque. Libero justo laoreet sit amet cursus.
            </Container>
        </div>
    );
}
 
export default Home;